name: Test Staging Build+GitHub
on:
  workflow_dispatch:

jobs:
  test:
    name: Check staging build + gh-pages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      #- shell: bash
      #  run: sudo cp -p retype-stub.sh /usr/local/bin/retype

      - name: Sets a variable with the repository name, stripping out owner/organization
        id: clean-repo-name
        shell: bash
        run: |
          echo "Setting repository_name as '${GITHUB_REPOSITORY#${{ github.repository_owner }}/}'."
          echo "::set-output name=repository_name::${GITHUB_REPOSITORY#${{ github.repository_owner }}/}"

      - uses: fabriciomurta/ragha-build@issue-11
        id: ragha-build
        with:
          base: "${{ steps.clean-repo-name.outputs.repository_name }}"
          #license: some-test-license

      - shell: bash
        env:
          MY_ENV_TO_RETYPE_PATH: ${{ steps.ragha-build.outputs.retype-output-path }}
        run: echo "Retype output is available at '${MY_ENV_TO_RETYPE_PATH}'."

      - uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.ragha-build.outputs.retype-output-path }}
          retention-days: 1

      - uses: fabriciomurta/ragha-github@v1
        with:
          branch: gh-pages
          #directory: docs
          update-branch: true
          #github-token: ${{ secrets.GITHUB_TOKEN }}

  test-issue-2:
    name: Checks issue-2 (wd/retypejson-path)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - uses: fabriciomurta/ragha-build@issue-2
        name: Push root with tests directory + test docs all-in-one
        with:
          base: ragha-tests
      - uses: fabriciomurta/ragha-github@master
        with:
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

# 1
      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 1.0: config: test1 dir'
        with:
          config: test1
          base: ragha-tests/test1.0

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test1.0
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 1.1: config: test1/retype.json'
        with:
          config: test1/retype.json
          base: ragha-tests/test1.1

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test1.1
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 1.2: config: ./test1 dir'
        with:
          config: ./test1
          base: ragha-tests/test1.2

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test1.2
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 1.3: config: ./test1/retype.json'
        with:
          config: ./test1/retype.json
          base: ragha-tests/test1.3

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test1.3
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 1.4: config: test1/ dir'
        with:
          config: test1/
          base: ragha-tests/test1.4

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test1.4
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 1.5: config: ./test1/'
        with:
          config: test1/retype.json
          base: ragha-tests/test1.5

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test1.5
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

# 2
      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 2.0.0: config: test2 dir'
        with:
          config: test2
          base: ragha-tests/test2.0.0

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test2.0.0
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 2.0.1: config: test2/retype.json'
        with:
          config: test2/retype.json
          base: ragha-tests/test2.0.1

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test2.0.1
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 2.1.0: config: test2/test21'
        with:
          config: test2/test21
          base: ragha-tests/test2.1.0

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test2.1.0
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 2.1.1: config: test2/test21/retype.json'
        with:
          config: test2/test21/retype.json
          base: ragha-tests/test2.1.1

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test2.1.1
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 2.1.2: config: ./test2/test21'
        with:
          config: ./test2/test21
          base: ragha-tests/test2.1.2

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test2.1.2
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 2.1.3: config: ./test2/test21/retype.json'
        with:
          config: ./test2/test21/retype.json
          base: ragha-tests/test2.1.3

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test2.1.3
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 2.1.4: config: ./test2/test21/'
        with:
          config: ./test2/test21/
          base: ragha-tests/test2.1.4

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test2.1.4
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 2.1.5: config: ./test1/../test2/test21/'
        with:
          config: ./test1/../test2/test21/
          base: ragha-tests/test2.1.5

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test2.1.5
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

# 3
      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 3.0: config: test3/retype-custom.json'
        with:
          config: test3/retype-custom.json
          base: ragha-tests/test3.0

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test3.0
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 3.1: config: test3/unrelated.txt'
        with:
          config: test3/unrelated.txt
          base: ragha-tests/test3.1

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test3.1
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 3.2: config: test3/extensionless'
        with:
          config: test3/extensionless
          base: ragha-tests/test3.2

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test3.2
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 3.3: config: test3/not-a-doc.md'
        with:
          config: test3/not-a-doc.md
          base: ragha-tests/test3.3

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test3.3
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

# 4
      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 4.0: config: test1/../test2/test21/../../test4'
        with:
          config: test1/../test2/test21/../../test4
          base: ragha-tests/test4.0

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test4.0
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 4.1: config: ./test4/test41/..'
        with:
          config: ./test4/test41/..
          base: ragha-tests/test4.1

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test4.1
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 4.2: config: ./test4/test41/../'
        with:
          config: ./test4/test41/../
          base: ragha-tests/test4.2

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test4.2
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 4.3: config: ./test4/test41/../retype.json'
        with:
          config: ./test4/test41/../retype.json
          base: ragha-tests/test4.3

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test4.3
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 4.4: config: test4/test41/../retype.json'
        with:
          config: test4/test41/../retype.json
          base: ragha-tests/test4.4

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test4.4
          update-branch: true