name: Test RAGHA Build+GitHub Actions
on:
  workflow_dispatch:

jobs:
  test:
    name: Check build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - shell: bash
        run: sudo cp -p retype-stub.sh /usr/local/bin/retype

      - uses: fabriciomurta/ragha-build@issue-1

      - uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.build1.outputs.retype-output-root }}