name: Test RAGHA Build Action
on:
  workflow_dispatch:

jobs:
  test:
    name: Check build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - uses: fabriciomurta/ragha-build@master
        id: retype-build

      - uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.retype-build.outputs.retype-output-root }}/output**