name: Test RAGHA Build+GitHub Actions
on:
  workflow_dispatch:

jobs:
  test:
    name: Check build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - uses: fabriciomurta/ragha-build@v1

      - uses: fabriciomurta/ragha-github@v1
        with:
          directory: docs