name: Test Staging Build+GitHub
on:
  workflow_dispatch:

jobs:
  test:
    name: Check staging build + gh-pages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      #- uses: actions/setup-dotnet@v1
      #  with:
      #    dotnet-version: 5.0.x

      #- shell: bash
      #  run: sudo cp -p retype-stub.sh /usr/local/bin/retype

      - name: Sets a variable with the repository name, stripping out owner/organization
        id: clean-repo-name
        shell: bash
        run: |
          echo "Setting repository_name as '${GITHUB_REPOSITORY#${{ github.repository_owner }}/}'."
          echo "::set-output name=repository_name::${GITHUB_REPOSITORY#${{ github.repository_owner }}/}"

      - uses: fabriciomurta/ragha-build@v1-warn
        id: ragha-build
        with:
          license: ${{ secrets.RETYPE_LICENSE_KEY }}

      #- shell: bash
      #  env:
      #    MY_ENV_TO_RETYPE_PATH: ${{ steps.ragha-build.outputs.retype-output-path }}
      #  run: echo "Retype output is available at '${MY_ENV_TO_RETYPE_PATH}'."

      #- uses: actions/upload-artifact@v2
      #  with:
      #    path: ${{ steps.ragha-build.outputs.retype-output-path }}
      #    retention-days: 1
