name: Test Staging Build+GitHub
on:
  workflow_dispatch:

jobs:
  test:
    name: Check staging build + gh-pages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      #- shell: bash
      #  run: sudo cp -p retype-stub.sh /usr/local/bin/retype

      - name: Sets a variable with the repository name, stripping out owner/organization
        id: clean-repo-name
        shell: bash
        run: |
          echo "Setting repository_name as '${GITHUB_REPOSITORY#${{ github.repository_owner }}/}'."
          echo "::set-output name=repository_name::${GITHUB_REPOSITORY#${{ github.repository_owner }}/}"

      - uses: fabriciomurta/ragha-build@v1
        id: ragha-build
        with:
          base: "${{ steps.clean-repo-name.outputs.repository_name }}"
          #license: some-test-license

      - shell: bash
        env:
          MY_ENV_TO_RETYPE_PATH: ${{ steps.ragha-build.outputs.retype-output-path }}
        run: echo "Retype output is available at '${MY_ENV_TO_RETYPE_PATH}'."

      - uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.ragha-build.outputs.retype-output-path }}
          retention-days: 1

      - uses: fabriciomurta/ragha-github@v1
        with:
          branch: gh-pages
          #directory: docs
          update-branch: true
          #github-token: ${{ secrets.GITHUB_TOKEN }}

  general-tests:
    name: Runs several random retype build tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - uses: fabriciomurta/ragha-build@v1
        name: Push root with tests directory + test docs all-in-one
        with:
          base: ragha-tests
      - uses: fabriciomurta/ragha-github@v1
        with:
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

# 1
      - uses: fabriciomurta/ragha-build@v1
        name: 'Test 1.0: config: test1 dir'
        with:
          config: test1
          base: ragha-tests/test1.0

      - uses: fabriciomurta/ragha-github@v1
        with:
          directory: test1.0
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@v1
        name: 'Test 1.1: config: test1/retype.json'
        with:
          config: test1/retype.json
          base: ragha-tests/test1.1

      - uses: fabriciomurta/ragha-github@v1
        with:
          directory: test1.1
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@v1
        name: 'Test 1.2: config: ./test1 dir'
        with:
          config: ./test1
          base: ragha-tests/test1.2

      - uses: fabriciomurta/ragha-github@v1
        with:
          directory: test1.2
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@v1
        name: 'Test 1.3: config: ./test1/retype.json'
        with:
          config: ./test1/retype.json
          base: ragha-tests/test1.3

      - uses: fabriciomurta/ragha-github@v1
        with:
          directory: test1.3
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@v1
        name: 'Test 1.4: config: test1/ dir'
        with:
          config: test1/
          base: ragha-tests/test1.4

      - uses: fabriciomurta/ragha-github@v1
        with:
          directory: test1.4
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@v1
        name: 'Test 1.5: config: ./test1/'
        with:
          config: test1/retype.json
          base: ragha-tests/test1.5

      - uses: fabriciomurta/ragha-github@v1
        with:
          directory: test1.5
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

# 2
      - uses: fabriciomurta/ragha-build@v1
        name: 'Test 2.0.0: config: test2 dir'
        with:
          config: test2
          base: ragha-tests/test2.0.0

      - uses: fabriciomurta/ragha-github@v1
        with:
          directory: test2.0.0
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@v1
        name: 'Test 2.0.1: config: test2/retype.json'
        with:
          config: test2/retype.json
          base: ragha-tests/test2.0.1

      - uses: fabriciomurta/ragha-github@v1
        with:
          directory: test2.0.1
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@v1
        name: 'Test 2.1.0: config: test2/test21'
        with:
          config: test2/test21
          base: ragha-tests/test2.1.0

      - uses: fabriciomurta/ragha-github@v1
        with:
          directory: test2.1.0
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@v1
        name: 'Test 2.1.1: config: test2/test21/retype.json'
        with:
          config: test2/test21/retype.json
          base: ragha-tests/test2.1.1

      - uses: fabriciomurta/ragha-github@v1
        with:
          directory: test2.1.1
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@v1
        name: 'Test 2.1.2: config: ./test2/test21'
        with:
          config: ./test2/test21
          base: ragha-tests/test2.1.2

      - uses: fabriciomurta/ragha-github@v1
        with:
          directory: test2.1.2
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@v1
        name: 'Test 2.1.3: config: ./test2/test21/retype.json'
        with:
          config: ./test2/test21/retype.json
          base: ragha-tests/test2.1.3

      - uses: fabriciomurta/ragha-github@v1
        with:
          directory: test2.1.3
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@v1
        name: 'Test 2.1.4: config: ./test2/test21/'
        with:
          config: ./test2/test21/
          base: ragha-tests/test2.1.4

      - uses: fabriciomurta/ragha-github@v1
        with:
          directory: test2.1.4
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@v1
        name: 'Test 2.1.5: config: ./test1/../test2/test21/'
        with:
          config: ./test1/../test2/test21/
          base: ragha-tests/test2.1.5

      - uses: fabriciomurta/ragha-github@v1
        with:
          directory: test2.1.5
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

# 3
      - uses: fabriciomurta/ragha-build@v1
        name: 'Test 3.0: config: test3/retype-custom.json'
        with:
          config: test3/retype-custom.json
          base: ragha-tests/test3.0

      - uses: fabriciomurta/ragha-github@v1
        with:
          directory: test3.0
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@v1
        name: 'Test 3.1: config: test3/unrelated.txt'
        with:
          config: test3/unrelated.txt
          base: ragha-tests/test3.1

      - uses: fabriciomurta/ragha-github@v1
        with:
          directory: test3.1
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@v1
        name: 'Test 3.2: config: test3/extensionless'
        with:
          config: test3/extensionless
          base: ragha-tests/test3.2

      - uses: fabriciomurta/ragha-github@v1
        with:
          directory: test3.2
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@v1
        name: 'Test 3.3: config: test3/not-a-doc.md'
        with:
          config: test3/not-a-doc.md
          base: ragha-tests/test3.3

      - uses: fabriciomurta/ragha-github@v1
        with:
          directory: test3.3
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

# 4
      - uses: fabriciomurta/ragha-build@v1
        name: 'Test 4.0: config: test1/../test2/test21/../../test4'
        with:
          config: test1/../test2/test21/../../test4
          base: ragha-tests/test4.0

      - uses: fabriciomurta/ragha-github@v1
        with:
          directory: test4.0
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@v1
        name: 'Test 4.1: config: ./test4/test41/..'
        with:
          config: ./test4/test41/..
          base: ragha-tests/test4.1

      - uses: fabriciomurta/ragha-github@v1
        with:
          directory: test4.1
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@v1
        name: 'Test 4.2: config: ./test4/test41/../'
        with:
          config: ./test4/test41/../
          base: ragha-tests/test4.2

      - uses: fabriciomurta/ragha-github@v1
        with:
          directory: test4.2
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@v1
        name: 'Test 4.3: config: ./test4/test41/../retype.json'
        with:
          config: ./test4/test41/../retype.json
          base: ragha-tests/test4.3

      - uses: fabriciomurta/ragha-github@v1
        with:
          directory: test4.3
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@v1
        name: 'Test 4.4: config: test4/test41/../retype.json'
        with:
          config: test4/test41/../retype.json
          base: ragha-tests/test4.4

      - uses: fabriciomurta/ragha-github@v1
        with:
          directory: test4.4
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

# 5
      - name: 'Test 5.1: Assemble project batch'
        shell: bash
        run: |
          cd test5
          ./run.sh

      - uses: fabriciomurta/ragha-build@v1
        name: 'Test 5.2: Rebuild "hub" project using build action'
        with:
          config: test5/hub
          base: ragha-tests/test5-hub

      - uses: fabriciomurta/ragha-github@v1
        name: 'Test 5.2.1: Push the built "hub" project to GitHub'
        with:
          directory: test5-hub
          update-branch: true

  test-git-ftp:
    name: Checks git-ftp action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - uses: fabriciomurta/ragha-build@v1
        name: test-gf-01 - Builds root retype project
        with:
          base: test-gf-01

      - uses: fabriciomurta/ragha-git-ftp@v1
        name: test-gf-01 - Uploads root built project using git-ftp into /test-gf-01
        with:
          branch: test-gf
          directory: test-gf-01
          ftp-host: ${{ secrets.ARVIXE_FTP_HOST }}
          ftp-pass: ${{ secrets.ARVIXE_FTP_PASS }}
          # the setup account has / as the http root
          ftp-root: /test-gf-01
          ftp-user: ${{ secrets.ARVIXE_FTP_USER }}
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@v1
        name: test-gf-02 - Builds the 'test1' retype project
        with:
          base: test-gf-02
          config: test1/retype.json

      - uses: fabriciomurta/ragha-git-ftp@v1
        name: test-gf-02 - Uploads test1 built project using git-ftp into /test-gf-02
        with:
          branch: test-gf
          directory: test-gf-02
          ftp-host: ${{ secrets.ARVIXE_FTP_HOST }}
          ftp-pass: ${{ secrets.ARVIXE_FTP_PASS }}
          # the setup account has / as the http root
          ftp-root: /test-gf-02
          ftp-user: ${{ secrets.ARVIXE_FTP_USER }}
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@v1
        name: test-gf-03 - Builds the 'test2' retype project
        with:
          base: test-gf-03
          config: test2/retype.json

      - uses: fabriciomurta/ragha-git-ftp@v1
        name: test-gf-03 - Uploads test2 built project using git-ftp into /test-gf-03
        with:
          #directory: / # place in specified branch's root
          branch: retype-test-gf-03
          ftp-host: ${{ secrets.ARVIXE_FTP_HOST }}
          ftp-pass: ${{ secrets.ARVIXE_FTP_PASS }}
          # the setup account has / as the http root
          ftp-root: /test-gf-03
          ftp-user: ${{ secrets.ARVIXE_FTP_USER }}
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@v1
        name: test-gf-04 - Builds the 'test1' retype project
        with:
          base: test-gf-04
          config: test1/retype.json

      - uses: fabriciomurta/ragha-github@v1
        name: test-gf-04 - Push built page to a branch as if it were a GitHub-Pages one
        with:
          branch: test-gf-04
          update-branch: true

      - uses: fabriciomurta/ragha-git-ftp@v1
        name: test-gf-04 - Uploads test1 built project using git-ftp into /test-gf-04
        with:
          #directory: / # place in specified branch's root
          branch: test-gf-04
          ftp-host: ${{ secrets.ARVIXE_FTP_HOST }}
          ftp-pass: ${{ secrets.ARVIXE_FTP_PASS }}
          # the setup account has / as the http root
          ftp-root: /test-gf-04
          ftp-user: ${{ secrets.ARVIXE_FTP_USER }}
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@v1
        name: test-gf-05 - Builds the 'test3' retype project
        with:
          base: test-gf-05
          config: test3/retype-custom.json

      - uses: fabriciomurta/ragha-github@v1
        name: test-gf-05 - Calls github-pages on specific dir within default test branch
        with:
          branch: test-gf
          directory: test-gf-05
          update-branch: true

      - uses: fabriciomurta/ragha-git-ftp@v1
        name: test-gf-05 - Calls git-ftp on same dir/branch as above
        with:
          branch: test-gf
          directory: test-gf-05
          ftp-host: ${{ secrets.ARVIXE_FTP_HOST }}
          ftp-pass: ${{ secrets.ARVIXE_FTP_PASS }}
          # the setup account has / as the http root
          ftp-root: /test-gf-05
          ftp-user: ${{ secrets.ARVIXE_FTP_USER }}
          update-branch: true
