name: Test Production Build+GitHub actions
on:
  workflow_dispatch:

jobs:
  test:
    name: Check production build + gh-pages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sets a variable with the repository name, stripping out owner/organization
        id: clean-repo-name
        shell: bash
        run: |
          echo "Setting repository_name as '${GITHUB_REPOSITORY#${{ github.repository_owner }}/}'."
          echo "::set-output name=repository_name::${GITHUB_REPOSITORY#${{ github.repository_owner }}/}"

      - uses: retypeapp/action-build@v1-warn
        id: retypeapp-action-build
        with:
          title: "Coo\"lPr'oj"
          base: "${{ steps.clean-repo-name.outputs.repository_name }}"

      - run: |
          retype --version

      - uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.retypeapp-action-build.outputs.retype-output-path }}
          retention-days: 1

      - uses: retypeapp/action-github-pages@v1
        with:
          branch: gh-pages
          update-branch: true
          #github-token: ${{ secrets.GITHUB_TOKEN }} # used only if update-branch is not true