name: Test RAGHA Build+GitHub Actions
on:
  workflow_dispatch:

jobs:
  test:
    name: Check ragha-github for update-branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - shell: bash
        run: sudo cp -p retype-stub.sh /usr/local/bin/retype

      - uses: fabriciomurta/ragha-build@v1.2
        with:
          project-name: "Coo\"lPr'oj"
          base: "ragha-test"
          license: ${{ secrets.RETYPE_LICENSE_KEY }}
        id: build1

      - uses: fabriciomurta/ragha-github@vDir
        with:
          branch: gh-subpages
          directory: docs
          update-branch: true
          github-token: ${{ secrets.GITHUB_TOKEN }}