name: Test RAGHA Build+GitHub staging Actions
on:
  workflow_dispatch:

jobs:
  test:
    name: Check RAGHA Action for build+github-pages @v1.

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      #- shell: bash
      #  run: sudo cp -p retype-stub.sh /usr/local/bin/retype

      - uses: fabriciomurta/ragha-build@v1
        with:
          title: "Coo\"lPr'oj"
          base: "ragha-test"
        id: build1

      - uses: fabriciomurta/ragha-github@v1
        with:
          branch: gh-pages
          directory: docs
          update-branch: true
          github-token: ${{ secrets.GITHUB_TOKEN }}