name: Test Staging Build+GitHub
on:
  workflow_dispatch:

jobs:
  test:
    name: Check staging build + gh-pages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - shell: bash
        run: sudo cp -p retype-stub.sh /usr/local/bin/retype

      - name: Sets a variable with the repository name, stripping out owner/organization
        id: clean-repo-name
        shell: bash
        run: echo "::set-output name=repository_name::${GITHUB_REPOSITORY#${{ github.repository_owner }}/}"

      - uses: fabriciomurta/ragha-build@v1
        with:
          title: "Coo\"lSt'aj"
          base: "${{ steps.clean-repo-name.outputs.repository_name }}"
          license: some-test-license
        id: build1

      - uses: fabriciomurta/ragha-github@v1
        with:
          branch: gh-pages
          #directory: docs
          update-branch: true
          #github-token: ${{ secrets.GITHUB_TOKEN }}