name: Test Production Build+GitHub actions
on:
  workflow_dispatch:

jobs:
  test:
    name: Check production build + gh-pages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      #- shell: bash
      #  run: sudo cp -p retype-stub.sh /usr/local/bin/retype

      - uses: retypeapp/action-build@v1
        with:
          title: "Coo\"lPr'oj"
          base: "ragha-test"
        id: build1

      - uses: retypeapp/action-github-pages@v1
        with:
          branch: gh-pages
          update-branch: true
          #github-token: ${{ secrets.GITHUB_TOKEN }} # used only if update-branch is not true