name: Test Staging Build+GitHub
on:
  workflow_dispatch:

jobs:
  test:
    name: Check staging build + gh-pages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      #- shell: bash
      #  run: sudo cp -p retype-stub.sh /usr/local/bin/retype

      - name: Sets a variable with the repository name, stripping out owner/organization
        id: clean-repo-name
        shell: bash
        run: |
          echo "Setting repository_name as '${GITHUB_REPOSITORY#${{ github.repository_owner }}/}'."
          echo "::set-output name=repository_name::${GITHUB_REPOSITORY#${{ github.repository_owner }}/}"

      - uses: fabriciomurta/ragha-build@v1
        id: ragha-build
        with:
          title: "Coo\"lSt'aj"
          base: "${{ steps.clean-repo-name.outputs.repository_name }}"
          #license: some-test-license

      - shell: bash
        env:
          MY_ENV_TO_RETYPE_PATH: ${{ steps.ragha-build.outputs.retype-output-path }}
        run: echo "Retype output is available at '${MY_ENV_TO_RETYPE_PATH}'."

      - uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.ragha-build.outputs.retype-output-path }}
          retention-days: 1

      - uses: fabriciomurta/ragha-github@v1
        with:
          branch: gh-pages
          #directory: docs
          update-branch: true
          #github-token: ${{ secrets.GITHUB_TOKEN }}

  test-issue-2:
    name: Checks issue-2 (wd/retypejson-path)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - uses: fabriciomurta/ragha-build@issue-2
        name: Push root with tests directory + test docs all-in-one
        with:
          base: ragha-build
      - uses: fabriciomurta/ragha-github@master
        with:
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

# 1
      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 1.0: Documentation from test1/ dir wd-based'
        with:
          wd: test1
          base: ragha-build/test1.0

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test1.0
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 1.1: Documentation from test1/ dir path-based'
        with:
          retypejson-path: test1/retype.json
          base: ragha-build/test1.1

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test1.1
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

# 2
      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 2.0.0: Documentation from test2/ dir wd-based'
        with:
          wd: test2
          base: ragha-build/test2.0.0

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test2.0.0
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 2.0.1: Documentation from test2/ dir path-based'
        with:
          retypejson-path: test2/retype.json
          base: ragha-build/test2.0.1

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test2.0.1
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 2.1.0: Documentation from test2/test21/ dir wd-based'
        with:
          wd: test2/test21
          base: ragha-build/test2.1.0

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test2.1.0
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 2.1.1: Documentation from test1/ dir path-based'
        with:
          retypejson-path: test2/test21/retype.json
          base: ragha-build/test2.1.1

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test2.1.1
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

# 3
      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 3.0: Documentation from test1/ dir wd-based'
        with:
          wd: test3
          base: ragha-build/test3.0

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test3.0
          update-branch: true

      - name: revert git tree to action ref
        run: git checkout ${{ github.sha }}

      - uses: fabriciomurta/ragha-build@issue-2
        name: 'Test 3.1: Documentation from test1/ dir path-based'
        with:
          retypejson-path: test3/retype.json
          base: ragha-build/test3.1

      - uses: fabriciomurta/ragha-github@master
        with:
          directory: test3.1
          update-branch: true
